/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.enpit.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Pamphlet service. Represents a row in the &quot;Pamphlet_Pamphlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>jp.co.enpit.model.impl.PamphletModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>jp.co.enpit.model.impl.PamphletImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pamphlet
 * @generated
 */
@ProviderType
public interface PamphletModel
	extends BaseModel<Pamphlet>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pamphlet model instance should use the {@link Pamphlet} interface instead.
	 */

	/**
	 * Returns the primary key of this pamphlet.
	 *
	 * @return the primary key of this pamphlet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pamphlet.
	 *
	 * @param primaryKey the primary key of this pamphlet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this pamphlet.
	 *
	 * @return the uuid of this pamphlet
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this pamphlet.
	 *
	 * @param uuid the uuid of this pamphlet
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the pamphlet ID of this pamphlet.
	 *
	 * @return the pamphlet ID of this pamphlet
	 */
	public long getPamphletId();

	/**
	 * Sets the pamphlet ID of this pamphlet.
	 *
	 * @param pamphletId the pamphlet ID of this pamphlet
	 */
	public void setPamphletId(long pamphletId);

	/**
	 * Returns the group ID of this pamphlet.
	 *
	 * @return the group ID of this pamphlet
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this pamphlet.
	 *
	 * @param groupId the group ID of this pamphlet
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this pamphlet.
	 *
	 * @return the company ID of this pamphlet
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this pamphlet.
	 *
	 * @param companyId the company ID of this pamphlet
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this pamphlet.
	 *
	 * @return the user ID of this pamphlet
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this pamphlet.
	 *
	 * @param userId the user ID of this pamphlet
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this pamphlet.
	 *
	 * @return the user uuid of this pamphlet
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this pamphlet.
	 *
	 * @param userUuid the user uuid of this pamphlet
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this pamphlet.
	 *
	 * @return the user name of this pamphlet
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this pamphlet.
	 *
	 * @param userName the user name of this pamphlet
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this pamphlet.
	 *
	 * @return the create date of this pamphlet
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this pamphlet.
	 *
	 * @param createDate the create date of this pamphlet
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this pamphlet.
	 *
	 * @return the modified date of this pamphlet
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this pamphlet.
	 *
	 * @param modifiedDate the modified date of this pamphlet
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the location ID of this pamphlet.
	 *
	 * @return the location ID of this pamphlet
	 */
	public long getLocationId();

	/**
	 * Sets the location ID of this pamphlet.
	 *
	 * @param locationId the location ID of this pamphlet
	 */
	public void setLocationId(long locationId);

	/**
	 * Returns the content of this pamphlet.
	 *
	 * @return the content of this pamphlet
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this pamphlet.
	 *
	 * @param content the content of this pamphlet
	 */
	public void setContent(String content);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(jp.co.enpit.model.Pamphlet pamphlet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<jp.co.enpit.model.Pamphlet> toCacheModel();

	@Override
	public jp.co.enpit.model.Pamphlet toEscapedModel();

	@Override
	public jp.co.enpit.model.Pamphlet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}