/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.co.enpit.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import jp.co.enpit.model.Pamphlet;
import jp.co.enpit.model.PamphletModel;
import jp.co.enpit.model.PamphletSoap;

/**
 * The base model implementation for the Pamphlet service. Represents a row in the &quot;Pamphlet_Pamphlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>PamphletModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PamphletImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PamphletImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class PamphletModelImpl
	extends BaseModelImpl<Pamphlet> implements PamphletModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pamphlet model instance should use the <code>Pamphlet</code> interface instead.
	 */
	public static final String TABLE_NAME = "Pamphlet_Pamphlet";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"pamphletId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"locationId", Types.BIGINT}, {"content", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pamphletId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("locationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("content", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Pamphlet_Pamphlet (uuid_ VARCHAR(75) null,pamphletId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,locationId LONG,content VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Pamphlet_Pamphlet";

	public static final String ORDER_BY_JPQL =
		" ORDER BY pamphlet.modifiedDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Pamphlet_Pamphlet.modifiedDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		jp.co.enpit.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.jp.co.enpit.model.Pamphlet"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		jp.co.enpit.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.jp.co.enpit.model.Pamphlet"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		jp.co.enpit.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.jp.co.enpit.model.Pamphlet"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long LOCATIONID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Pamphlet toModel(PamphletSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Pamphlet model = new PamphletImpl();

		model.setUuid(soapModel.getUuid());
		model.setPamphletId(soapModel.getPamphletId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setLocationId(soapModel.getLocationId());
		model.setContent(soapModel.getContent());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Pamphlet> toModels(PamphletSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Pamphlet> models = new ArrayList<Pamphlet>(soapModels.length);

		for (PamphletSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		jp.co.enpit.service.util.ServiceProps.get(
			"lock.expiration.time.jp.co.enpit.model.Pamphlet"));

	public PamphletModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _pamphletId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPamphletId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _pamphletId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Pamphlet.class;
	}

	@Override
	public String getModelClassName() {
		return Pamphlet.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Pamphlet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Pamphlet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Pamphlet, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Pamphlet)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Pamphlet, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Pamphlet, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Pamphlet)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Pamphlet, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Pamphlet, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Pamphlet>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Pamphlet.class.getClassLoader(), Pamphlet.class,
			ModelWrapper.class);

		try {
			Constructor<Pamphlet> constructor =
				(Constructor<Pamphlet>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Pamphlet, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Pamphlet, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Pamphlet, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Pamphlet, Object>>();
		Map<String, BiConsumer<Pamphlet, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Pamphlet, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object uuid) {
					pamphlet.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"pamphletId",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getPamphletId();
				}

			});
		attributeSetterBiConsumers.put(
			"pamphletId",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object pamphletId) {
					pamphlet.setPamphletId((Long)pamphletId);
				}

			});
		attributeGetterFunctions.put(
			"groupId",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getGroupId();
				}

			});
		attributeSetterBiConsumers.put(
			"groupId",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object groupId) {
					pamphlet.setGroupId((Long)groupId);
				}

			});
		attributeGetterFunctions.put(
			"companyId",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getCompanyId();
				}

			});
		attributeSetterBiConsumers.put(
			"companyId",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object companyId) {
					pamphlet.setCompanyId((Long)companyId);
				}

			});
		attributeGetterFunctions.put(
			"userId",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getUserId();
				}

			});
		attributeSetterBiConsumers.put(
			"userId",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object userId) {
					pamphlet.setUserId((Long)userId);
				}

			});
		attributeGetterFunctions.put(
			"userName",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getUserName();
				}

			});
		attributeSetterBiConsumers.put(
			"userName",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object userName) {
					pamphlet.setUserName((String)userName);
				}

			});
		attributeGetterFunctions.put(
			"createDate",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getCreateDate();
				}

			});
		attributeSetterBiConsumers.put(
			"createDate",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object createDate) {
					pamphlet.setCreateDate((Date)createDate);
				}

			});
		attributeGetterFunctions.put(
			"modifiedDate",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getModifiedDate();
				}

			});
		attributeSetterBiConsumers.put(
			"modifiedDate",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object modifiedDate) {
					pamphlet.setModifiedDate((Date)modifiedDate);
				}

			});
		attributeGetterFunctions.put(
			"locationId",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getLocationId();
				}

			});
		attributeSetterBiConsumers.put(
			"locationId",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object locationId) {
					pamphlet.setLocationId((Long)locationId);
				}

			});
		attributeGetterFunctions.put(
			"content",
			new Function<Pamphlet, Object>() {

				@Override
				public Object apply(Pamphlet pamphlet) {
					return pamphlet.getContent();
				}

			});
		attributeSetterBiConsumers.put(
			"content",
			new BiConsumer<Pamphlet, Object>() {

				@Override
				public void accept(Pamphlet pamphlet, Object content) {
					pamphlet.setContent((String)content);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPamphletId() {
		return _pamphletId;
	}

	@Override
	public void setPamphletId(long pamphletId) {
		_pamphletId = pamphletId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getLocationId() {
		return _locationId;
	}

	@Override
	public void setLocationId(long locationId) {
		_columnBitmask |= LOCATIONID_COLUMN_BITMASK;

		if (!_setOriginalLocationId) {
			_setOriginalLocationId = true;

			_originalLocationId = _locationId;
		}

		_locationId = locationId;
	}

	public long getOriginalLocationId() {
		return _originalLocationId;
	}

	@JSON
	@Override
	public String getContent() {
		if (_content == null) {
			return "";
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Pamphlet.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Pamphlet.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Pamphlet toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PamphletImpl pamphletImpl = new PamphletImpl();

		pamphletImpl.setUuid(getUuid());
		pamphletImpl.setPamphletId(getPamphletId());
		pamphletImpl.setGroupId(getGroupId());
		pamphletImpl.setCompanyId(getCompanyId());
		pamphletImpl.setUserId(getUserId());
		pamphletImpl.setUserName(getUserName());
		pamphletImpl.setCreateDate(getCreateDate());
		pamphletImpl.setModifiedDate(getModifiedDate());
		pamphletImpl.setLocationId(getLocationId());
		pamphletImpl.setContent(getContent());

		pamphletImpl.resetOriginalValues();

		return pamphletImpl;
	}

	@Override
	public int compareTo(Pamphlet pamphlet) {
		int value = 0;

		value = DateUtil.compareTo(
			getModifiedDate(), pamphlet.getModifiedDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Pamphlet)) {
			return false;
		}

		Pamphlet pamphlet = (Pamphlet)obj;

		long primaryKey = pamphlet.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		PamphletModelImpl pamphletModelImpl = this;

		pamphletModelImpl._originalUuid = pamphletModelImpl._uuid;

		pamphletModelImpl._originalGroupId = pamphletModelImpl._groupId;

		pamphletModelImpl._setOriginalGroupId = false;

		pamphletModelImpl._originalCompanyId = pamphletModelImpl._companyId;

		pamphletModelImpl._setOriginalCompanyId = false;

		pamphletModelImpl._setModifiedDate = false;

		pamphletModelImpl._originalLocationId = pamphletModelImpl._locationId;

		pamphletModelImpl._setOriginalLocationId = false;

		pamphletModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Pamphlet> toCacheModel() {
		PamphletCacheModel pamphletCacheModel = new PamphletCacheModel();

		pamphletCacheModel.uuid = getUuid();

		String uuid = pamphletCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			pamphletCacheModel.uuid = null;
		}

		pamphletCacheModel.pamphletId = getPamphletId();

		pamphletCacheModel.groupId = getGroupId();

		pamphletCacheModel.companyId = getCompanyId();

		pamphletCacheModel.userId = getUserId();

		pamphletCacheModel.userName = getUserName();

		String userName = pamphletCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			pamphletCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			pamphletCacheModel.createDate = createDate.getTime();
		}
		else {
			pamphletCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			pamphletCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			pamphletCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		pamphletCacheModel.locationId = getLocationId();

		pamphletCacheModel.content = getContent();

		String content = pamphletCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			pamphletCacheModel.content = null;
		}

		return pamphletCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Pamphlet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Pamphlet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Pamphlet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Pamphlet)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Pamphlet, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Pamphlet, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Pamphlet, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Pamphlet)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, Pamphlet>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private String _uuid;
	private String _originalUuid;
	private long _pamphletId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _locationId;
	private long _originalLocationId;
	private boolean _setOriginalLocationId;
	private String _content;
	private long _columnBitmask;
	private Pamphlet _escapedModel;

}